### ISSUE TITLE
Not working on Chrome 

### ISSUE THREAD

**Issue by patrickhartono** [resonance-audio/resonance-audio-web-sdk#20] opened 2018-10-17 07:43 UTC
Hi, I tried to run the example fine on Google and it's not working, no sound at all. 

Does anyone experience the same problem?

**Comment by b2renger** [comment] 2018-10-17 08:19
@patrickhartono, yes I do as well, but it woks on Firefox right ?

it's probably related to this issue  : https://github.com/resonance-audio/resonance-audio-web-sdk/issues/16

**Comment by hoch** [comment] 2018-10-17 16:41
I suspect this might #16, but just to be sure - do you see anything in the console?

**Comment by patrickhartono** [comment] 2018-10-18 04:11
Hi, Guys @b2renger @hoch  Yes I #16  problem. 

Here what I found in the console: 

app.js:2 The Web Audio autoplay policy will be re-enabled in Chrome 71 (December 2018). Please check that your website is compatible with it. https://goo.gl/7K7WLu

Hopes they could fixed it before December LOL 


Thanks Guys!

**Comment by b2renger** [comment] 2018-10-18 09:20
@hoch 
Running locally with a server on my tests pages I get this error 

```
resonance-audio.min.js:121 Uncaught DOMException: Failed to set the 'buffer' property on 'ConvolverNode': Cannot set buffer to non-null after it has been already been set to a non-null buffer
    at i.setDurations (https://cdn.jsdelivr.net/npm/resonance-audio/build/resonance-audio.min.js:121:1062)
    at a.setProperties (https://cdn.jsdelivr.net/npm/resonance-audio/build/resonance-audio.min.js:106:116)
    at i.setRoomProperties (https://cdn.jsdelivr.net/npm/resonance-audio/build/resonance-audio.min.js:166:294)
    at setup (http://127.0.0.1:63230/week99_spatial_audio_test/sketch.js:56:25)
    at e.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:7:17527)
    at e.<anonymous> (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:7:16514)
    at new e (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:7:19898)
    at e (https://cdnjs.cloudflare.com/ajax/libs/p5.js/0.6.0/p5.min.js:7:28199)
```

**Comment by hoch** [comment] 2018-10-18 15:41
@patrickhartono What you found is not the root cause of the problem. It's just a warning that the autoplay policy will change in Chrome 71.

@b2renger Thanks for the confirmation. This issue is a duplicate of #16, so I am closing. Please follow the linked issue for the updates.

**Closed as completed** 2018-10-18 15:42 UTC
Labels: duplicate
